version: '3.8'

services:
  server:
    image: express-bloglist-dev-server
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes: 
      - ./backend/:/usr/src/app
  app: 
    image: bloglist-front-dev
    build: 
      context: ./frontend
      dockerfile: dev.Dockerfile
    container_name: blogList-front-dev
    volumes: 
      - ./frontend/:/usr/src/app
    environment:
      REACT_APP_BACKEND_URL: 'http://server:5000'
    ports:
      - 3003:3000
    depends_on:
      - server
